name: Deploy Backend to InterData Hosting 22-03-2026 - integrate export file excel

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️ Checkout source code
      - name: Get latest code
        uses: actions/checkout@v4

      # 2️ Deploy to InterData via FTP
      - name: Deploy to InterData via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.uniideas.io.vn
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          local-dir: ./   # hoặc thư mục chứa backend, ví dụ backend/
          server-dir: /public_html/api.uniideas.io.vn/
          dangerous-clean-slate: false
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
            **/tests/**
            **/.env
            **/vendor/**
